Add support for EGL_DEBUG_KHR extension
apitrace/apitrace pull request #916
Opened 2024-04-25 15:51 UTC by lfrb

2024-04-26 08:58 UTC, jrfonseca commented
@lfrb please rebase this and all your other PRs on top of https://github.com/apitrace/apitrace/commit/764c1f1d95123d38fd3f6b814da36482da4d8eb4 so mac64 build can succeed.

2024-05-02 16:19 UTC, jrfonseca requested changes
Otherwise looks good.

2024-05-02 16:19 UTC, jrfonseca commented on dispatch/glproc.py
> +            return
`eglQueryDebugKHR` returns a `EGLBoolean`.  You're missing a

```python
    print(r' return EGLFalse;')
```

Ditto for all the other functions that return values .

This should fix the MSVC builds.

2024-05-02 16:19 UTC, jrfonseca commented on specs/eglapi.py
> +    GlFunction(EGLBoolean, "eglQueryDebugKHR", [(EGLint, "attribute"), (OpaquePointer(EGLAttrib), "value")]),
`sideffects=False`

2024-05-02 16:19 UTC, jrfonseca commented on specs/eglapi.py
> +    GlFunction(EGLint, "eglDebugMessageControlKHR", [(EGLDEBUGPROCKHR, "callback"), (EGLDebugAttribs, "attrib_list")]),
sideeffects=False

2024-05-17 15:35 UTC, jrfonseca commented on dispatch/glproc.py
> +            return
Thanks for then update.  I mistyped, it should have been `return EGL_FALSE`.  I know 0 and `EGL_FALSE` is all the same from the compiler POV, but it's confusing from my POV.

2024-05-30 01:17 UTC, lfrb commented
@jrfonseca Anything else you would make to change to get it merged? Thanks :)

2024-05-30 13:01 UTC, jrfonseca commented
@lfrb I missed the update notification somehow.  Thank you for that.

2024-05-30 13:01 UTC, merged